ARG NODE_VERSION=12.22.1
FROM node:${NODE_VERSION}-slim
WORKDIR /node/uniapp-cli
ENV NODE_ENV=production \
    UNI_INPUT_DIR=/app \
    UNI_OUTPUT_DIR=/app/unpackage/dist/build/h5 \
    UNI_PLATFORM=h5
COPY app /demo
COPY plugins/ /node
RUN mkdir /tt && cd /tt && npm i node-sass-china && mkdir -p /node/compile-node-sass/node_modules/node-sass-china/vendor/linux-x64-72 &&cp ./node_modules/node-sass-china/vendor/linux-x64-72/binding.node /node/compile-node-sass/node_modules/node-sass-china/vendor/linux-x64-72
RUN node bin/uniapp-cli.js
CMD node bin/uniapp-cli.js --help

